export const SEPARATOR_TYPES = {
  COMMA: 'COMMA',
  TAB: 'TAB',
  SEMICOLON: 'SEMICOLON',
};

export const SEPARATOR_VALUES = {
  [SEPARATOR_TYPES.COMMA]: ',',
  [SEPARATOR_TYPES.TAB]: `  `,
  [SEPARATOR_TYPES.SEMICOLON]: ';',
};
